; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; SENSOR NODE
[env:sensor_node]
build_flags = 
    ${env.build_flags}
    -D SENSOR_NODE=1      ; Sensor ID flag
lib_deps = 
    DHT20-v0.3.1
    AdafruitNeoPixel-v1.15.1
    TensorFlowLiteESP32-v1.0.0
build_src_filter = 
    +<*> 
    -<web_server.cpp> 
    -<core_iot.cpp> 
    -<network_manager.cpp>
test_filter = test_sensor
test_build_src = yes

; GATEWAY NODE
[env:gateway_node]
build_flags = 
    ${env.build_flags}
    -D GATEWAY_NODE=1     ; Gateway ID flag
lib_deps = 
    ArduinoJson-v7.4.2
    ArduinoHttpClient-v0.6.1
    PubSubClient
    ThingsBoard-v0.12.0
build_src_filter = 
    +<*> 
    -<read_sensor.cpp> 
    -<tiny_ml.cpp> 
    -<lcd_display.cpp> 
    -<neo_pixel.cpp>
test_filter = test_gateway
test_build_src = yes